In [1]:
import ee
import geopandas as gpd
import pandas as pd

from pph import fpcde

In [2]:
ee.Initialize()

In [16]:
TARGET_ORBITS = [49, 34, 151, 107]
TARGET_Y = [52.17, 50.59, 49.64, 49.98, 50.69, 50.7]

In [6]:
aoi_filename = "../../data/pph_region.shp"
gdf_aoi = gpd.read_file(aoi_filename)
gdf_aoi.to_crs(4326, inplace=True)
ee_aoi = ee.FeatureCollection(gdf_aoi.__geo_interface__).geometry()

In [7]:
q_date = [(f"{date}-04-01", f"{date}-10-31" ) for date in range(2017, 2022)]

In [8]:
gdfs = [
    fpcde.Sentinel1Extractor().extract_and_process(ee_aoi, date)
    for date in q_date
]

In [19]:
gdf = pd.concat(gdfs)

In [20]:
gdf = gdf[(gdf['relativeOrbitNumber_start'].isin(TARGET_ORBITS)) & (gdf.y.isin(TARGET_Y))]
gdf

,system:id,y,x,relativeOrbitNumber_start,timestamp,year,datedif,geometry
148,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170507T00...,49.64,-100.59,34,2017-05-07 00:31:15+00:00,2017,0.0,"POLYGON ((-99.04324 50.56854, -99.04371 50.569..."
149,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170519T00...,49.64,-100.59,34,2017-05-19 00:31:16.180000067+00:00,2017,12.0,"POLYGON ((-102.07096 48.69879, -102.06624 48.6..."
150,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170531T00...,49.64,-100.59,34,2017-05-31 00:31:16+00:00,2017,12.0,"POLYGON ((-99.04266 50.56982, -99.22421 50.552..."
151,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170612T00...,49.64,-100.59,34,2017-06-12 00:31:17+00:00,2017,12.0,"POLYGON ((-101.20694 50.34043, -101.44357 50.3..."
152,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170624T00...,49.64,-100.58,34,2017-06-24 00:31:18+00:00,2017,12.0,"POLYGON ((-99.04103 50.56971, -99.04301 50.569..."
...,...,...,...,...,...,...,...,...
435,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210827T01...,52.17,-111.55,49,2021-08-27 01:13:36+00:00,2021,12.0,"POLYGON ((-113.61976 52.70853, -113.61808 52.7..."
436,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210908T01...,52.17,-111.54,49,2021-09-08 01:13:37+00:00,2021,12.0,"POLYGON ((-109.98023 53.22717, -109.99961 53.2..."
437,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210920T01...,52.17,-111.54,49,2021-09-20 01:13:37+00:00,2021,12.0,"POLYGON ((-113.10086 51.13548, -113.09816 51.1..."
438,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211014T01...,52.17,-111.55,49,2021-10-14 01:13:37+00:00,2021,24.0,"POLYGON ((-109.57876 51.52277, -109.55760 51.5..."
439,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211026T01...,52.17,-111.55,49,2021-10-26 01:13:37+00:00,2021,12.0,"POLYGON ((-113.10364 51.13498, -113.10155 51.1..."

In [21]:
gdf.head()

,system:id,y,x,relativeOrbitNumber_start,timestamp,year,datedif,geometry
148,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170507T00...,49.64,-100.59,34,2017-05-07 00:31:15+00:00,2017,0.0,"POLYGON ((-99.04324 50.56854, -99.04371 50.569..."
149,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170519T00...,49.64,-100.59,34,2017-05-19 00:31:16.180000067+00:00,2017,12.0,"POLYGON ((-102.07096 48.69879, -102.06624 48.6..."
150,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170531T00...,49.64,-100.59,34,2017-05-31 00:31:16+00:00,2017,12.0,"POLYGON ((-99.04266 50.56982, -99.22421 50.552..."
151,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170612T00...,49.64,-100.59,34,2017-06-12 00:31:17+00:00,2017,12.0,"POLYGON ((-101.20694 50.34043, -101.44357 50.3..."
152,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170624T00...,49.64,-100.58,34,2017-06-24 00:31:18+00:00,2017,12.0,"POLYGON ((-99.04103 50.56971, -99.04301 50.569..."

In [22]:
cols = [_ for _ in list(gdf.columns) if _ != 'geometry']
gdf = gdf[cols]
pd.DataFrame(gdf).to_csv("../../reports/fpc-s1-reports.csv")