In [1]:
import ee
import geopandas as gpd
import pandas as pd

from pph import fpcde

In [2]:
ee.Initialize()

In [3]:
TARGET_ORBIT = 49

In [4]:
aoi_filename = "../data/pph_region.shp"
gdf_aoi = gpd.read_file(aoi_filename)
gdf_aoi.to_crs(4326, inplace=True)

In [5]:
ee_aoi = ee.FeatureCollection(gdf_aoi.__geo_interface__).geometry()

In [6]:
q_date = [(f"{date}-04-01", f"{date}-10-31" ) for date in range(2017, 2022)]

In [7]:
gdfs = [
    fpcde.Sentinel1Extractor().extract_and_process(ee_aoi, date)
    for date in q_date
]

In [14]:
gdf = pd.concat(gdfs)

In [15]:
gdf = gdf[gdf['relativeOrbitNumber_start'] == TARGET_ORBIT]
gdf

,system:id,y,x,relativeOrbitNumber_start,timestamp,year,datedif,geometry
71,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170426T01...,49.10,-110.72,49,2017-04-26 01:12:14.450000048+00:00,2017,0.0,"POLYGON ((-112.17726 48.14475, -112.17656 48.1..."
72,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170508T01...,49.10,-110.72,49,2017-05-08 01:12:15.180000067+00:00,2017,12.0,"POLYGON ((-109.12972 48.50240, -108.84787 48.5..."
73,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170520T01...,49.10,-110.72,49,2017-05-20 01:12:15+00:00,2017,12.0,"POLYGON ((-108.84725 48.53135, -108.84720 48.5..."
74,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170601T01...,49.10,-110.72,49,2017-06-01 01:12:16+00:00,2017,12.0,"POLYGON ((-108.84718 48.53119, -108.84587 48.5..."
75,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170613T01...,49.10,-110.72,49,2017-06-13 01:12:17+00:00,2017,12.0,"POLYGON ((-109.26336 48.48844, -108.87714 48.5..."
...,...,...,...,...,...,...,...,...
435,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210827T01...,52.17,-111.55,49,2021-08-27 01:13:36+00:00,2021,12.0,"POLYGON ((-113.61976 52.70853, -113.61808 52.7..."
436,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210908T01...,52.17,-111.54,49,2021-09-08 01:13:37+00:00,2021,12.0,"POLYGON ((-109.98023 53.22717, -109.99961 53.2..."
437,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210920T01...,52.17,-111.54,49,2021-09-20 01:13:37+00:00,2021,12.0,"POLYGON ((-113.10086 51.13548, -113.09816 51.1..."
438,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211014T01...,52.17,-111.55,49,2021-10-14 01:13:37+00:00,2021,24.0,"POLYGON ((-109.57876 51.52277, -109.55760 51.5..."
439,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211026T01...,52.17,-111.55,49,2021-10-26 01:13:37+00:00,2021,12.0,"POLYGON ((-113.10364 51.13498, -113.10155 51.1..."

In [16]:
# unique y:
gdf.y.unique()

array([49.1 , 50.43, 50.59, 52.17, 52.18])

In [17]:
# 52.2 not in the target
# want 52.17
gdf = gdf[gdf.y.isin([50.59])]

In [18]:
cols = [_ for _ in list(gdf.columns) if _ != 'geometry']
gdf = gdf[cols]
gdf

,system:id,y,x,relativeOrbitNumber_start,timestamp,year,datedif
218,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170426T01...,50.59,-111.16,49,2017-04-26 01:12:39.450000048+00:00,2017,0.0
219,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170508T01...,50.59,-111.16,49,2017-05-08 01:12:40+00:00,2017,12.0
220,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170520T01...,50.59,-111.16,49,2017-05-20 01:12:40+00:00,2017,12.0
221,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170601T01...,50.59,-111.16,49,2017-06-01 01:12:41+00:00,2017,12.0
222,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20170613T01...,50.59,-111.16,49,2017-06-13 01:12:42+00:00,2017,12.0
...,...,...,...,...,...,...,...
266,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210827T01...,50.59,-111.13,49,2021-08-27 01:13:11+00:00,2021,12.0
267,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210908T01...,50.59,-111.13,49,2021-09-08 01:13:12+00:00,2021,12.0
268,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20210920T01...,50.59,-111.12,49,2021-09-20 01:13:12+00:00,2021,12.0
269,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211014T01...,50.59,-111.13,49,2021-10-14 01:13:12+00:00,2021,24.0
270,COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20211026T01...,50.59,-111.13,49,2021-10-26 01:13:12+00:00,2021,12.0

In [19]:
pd.DataFrame(gdf).to_csv("../reports/orbit_49.csv")

In [24]:
"_".join(["50.59"])

'50.59'